### ISSUE TITLE
getting error when use twitter and google

### ISSUE THREAD

**Issue by joanhard** [definitely246/social#1]
hi, I call Social::login('twitter') and Social::login('facebook') getting error message "Scopes passed to ServiceFactory::createService but an OAuth1 service was requested. "

how can fix it? 

facebook is work fine.
Thank you

**Comment by kdocki** [comment]
you are only seeing problems with Social::login('twitter') then?

**Comment by kdocki** [comment]
duplicate issue https://github.com/CodeSleeve/social/issues/2
