### ISSUE TITLE
Error with Twitter

### ISSUE THREAD

**Issue by domioanna** [definitely246/social#2]
Followed your instructions, but when testing Twitter, receive this message on Twitter site when forwarded

"There is no request token for this page. That's the special key we need from applications asking to use your Twitter account. Please go back to the site or application that sent you here and try again; it was probably just a mistake."

Any idea's what I might have missed?

**Comment by hectorcenteno** [comment]
I do have the same problem, We can expect no help for this ?

**Comment by kdocki** [comment]
I am not sure what is happening. What does your config file look like?

**Comment by hectorcenteno** [comment]
yes, my config files looks like this:

``` php
    'facebook' => array(
        'key' => 'my_facebook_key',
        'secret' => 'my_facebook_secret',
        'scopes' => array('email', 'read_requests', 'publish_actions'),
        'redirect_url' => '/start',
    ),
    'twitter' => array(
        'key' => 'my_twitter_key',
        'scopes' => array(),
        'secret' => 'my_twitter_secret',
        'redirect_url' => '/start'
    ),
```

Also I have a view with this:

``` html
<p><a href="<?php echo Social::login('twitter'); ?>">Twitter Signin</a></p>
```

You can see my implementation in: http://bestbuyapp.dommo.mx

The facebook one, works, but twitter not.

**Comment by hectorcenteno** [comment]
I see on the Twitter documentation there must be a process to access Twitter is a little bit more complex. https://dev.twitter.com/docs/auth/implementing-sign-twitter

Does this package support this process ?

**Comment by hectorcenteno** [comment]
I've been trying to figure this out, so based on the lusitanian\oauth demo the link generated with:

``` php
Social::login('twitter');
```

Should be routed to a controller method where this should happend:

``` php
$service = App::make('social')->twitter();
$token = $service->requestRequestToken();
$url = $service->getAuthorizationUri(array('oauth_token' => $token->getRequestToken()));
header('Location: ' . $url);
```

That $url is the url with the correct token so twitter is able to authorize the app.

But when I do it, I get this:

```
TokenResponseException

OAuth/Common/Http/Client/StreamClient.php Line 75
```

I understand it's an error on that class, but the example on this library is working, I been trying to discover the error, but almost all looks the same, I hope you have the time to check this out.

**Comment by tabennett** [comment]
This should be fixed now.

**Comment by mgufrone** [comment]
i got this problem too when i run my apps on windows, but in linux seems work. I don't know why, i use the same config, the same version.
